### ISSUE TITLE
Need Readme & Issue templates

### ISSUE THREAD

**Issue by BethMassi** [dotnet-foundation/events#1]
We need a way for members to request event sponsorship. We need a readme that describes how we prioritize (what we get for what we're giving) and and issue template on how to submit.  
i.e.
- What are we sponsoring? Does it promote .NET open source?
- What is the level of diversity at the event? Code of conduct we agree with?
- How many attendees are there? 
- What do we get for the money? i.e. logo somewhere? a booth?
- Is there an optional co-marketing opportunity (help promote each other) if we can't fund (fully)? 

@isaacrlevin you volunteered at the last meeting to get something going here.

**Comment by sfaatz** [comment]
Happy to help with this! @isaacrlevin - let me know if you want to schedule some time to chat so we can divide and conquer. I am on the east coast. Next week might be easier than this, but let me know what works for you and we can figure it out!

**Comment by BethMassi** [comment]
Thanks Sara! If you can make the next committee meeting (committee members only) then we can work discuss and work through it.

**Comment by isaacrlevin** [comment]
hey @sfaatz sounds really good, go ahead and find some time on my calendar
https://calendly.com/islevin/net-marketing-sync
